[versions]
txrpc = "2.6"

[libraries]
txrpc-runtime     = { module = "io.github.osobolev.txrpc:txrpc-runtime", version.ref = "txrpc" }
txrpc-server      = { module = "io.github.osobolev.txrpc:txrpc-remote-server", version.ref = "txrpc" }
txrpc-body-server = { module = "io.github.osobolev.txrpc:txrpc-body-server", version.ref = "txrpc" }

servlet-api = "javax.servlet:javax.servlet-api:3.1.0"
jetty = "org.eclipse.jetty:jetty-servlet:9.4.58.v20250814"
tomcat = "org.apache.tomcat.embed:tomcat-embed-core:9.0.115"
commons-compress = "org.apache.commons:commons-compress:1.28.0"
xz = "org.tukaani:xz:1.11"
